services:
   annotate:
      build: .
      ports:
         - "8888:${ANNOTATE_PORT}"
      volumes:
         - ${PWD}/save:/save:rw
         - ${PWD}/cache:/cache:rw
         - ${PWD}/config:/config:r
         - ${PWD}:/git:r
      environment:
        - DOCKER_STACKS_JUPYTER_CMD=notebook
