services:
   annotate:
      build: .
      ports:
         - "${ANNOTATE_PORT}:8888"
      volumes:
         - ${PWD}/src:/src
         - ${PWD}/save:/save
         - ${PWD}/cache:/cache
         - ${PWD}/config:/config
         - ${PWD}:/git
      environment:
        - DOCKER_STACKS_JUPYTER_CMD=notebook
